### ISSUE TITLE
Neovim support?

### ISSUE THREAD

**Issue by thornycrackers** [baverman/vial-http#3]
I tried this in vim and it worked but when I tried it in neovim I got the following error.

```
Error detected while processing function provider#python#Call:
line   18:
Invalid channel: 1
```

This might be a python version issue as well?

**Comment by baverman** [comment]
I'll try to support vial-http in neovim but it can be tricky.

I've fixed startup (you need to update https://github.com/baverman/vial) and managed to execute :VialHttp and get result but with some warnings. Also keymaps aren't work.

**Comment by baverman** [comment]
And there is issue with response windows, they loose content after switching to another buffer. Seems bug in python-neovim in LagacyVim implementation, I'll look for workaround.

**Comment by baverman** [comment]
Workaround for disappeared content: You need to  set ``hidden`` option.

**Comment by thornycrackers** [comment]
Thanks so much! Looks to be working 👍

**Comment by poupougnac** [comment]
I had to set : 
g:vial_python = 'python3'
to make it works with NeoVim.
