### ISSUE TITLE
Response Code : 302

### ISSUE THREAD

**Issue by ParadiseHell** [baverman/vial-http#6]
I just try to use vial-http with some **GET** requests.
But when the url is like **https://tmall.com** I get 302 which is what I don't want.
Although I know vial-http is for rest quests, I still think if it can hadle 302 it will better.

**Comment by baverman** [comment]
302 is unhandled by purpose to be able to see headers and location of intermediate responses. I'am think about special headers Vial-Connect, Vial-Timeout and also I can make Vial-Redirect to control automatic redirection.

**Comment by ParadiseHell** [comment]
Are you sure you had added automatic redirects?
First I have **updated** vial-http
And the **GET Request** : https://tmall.com
I still get 302 code using **vial-http**.
But when I use **wget**, I got this following : 

> HTTP request sent, awaiting response... 302 Found
> Location: https://www.tmall.com/ [following]

When I try to request this URL **https://www.tmall.com** using **vial-http**, it works.

So I think your way of automatic redirects still remains some bugs.

**Comment by ParadiseHell** [comment]
Your main code I found following : 
> url = resp.getheader('location')

But you see **wget** gets response following : 

> Location: https://www.tmall.com/

So I wonder that you may change **location** to **Location**.

**Comment by ParadiseHell** [comment]
I have tried to fork and change **location** to **Location**, but it still doesn't work, so I guess there may be some other bugs.

**Comment by baverman** [comment]
You have to set `Vial-Redirect` header.
```
Vial-Redirect: 1

GET https://tmall.com
```
https://github.com/baverman/vial-http/blob/master/doc/tutorial.rst#redirects
